# Generated by Django 3.0.4 on 2020-03-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='infected')),
                ('extention', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('logic', models.CharField(max_length=128)),
                ('issue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('TGT', 'Target'), ('ENG', 'Engine'), ('FSZ', 'FileSize'), ('ENT', 'EntryPoint'), ('SEC', 'NumberOfSections'), ('CON', 'Container'), ('INT', 'Intermediates')], max_length=3)),
                ('value', models.CharField(max_length=128)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.Signature')),
            ],
        ),
        migrations.CreateModel(
            name='SubSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('value', models.CharField(max_length=1024)),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('REG', 'Regular expression'), ('HEX', 'Hex string')], max_length=3)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.Signature')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('example', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('SIG', 'Malware signature'), ('WHT', 'Whitelist rules'), ('BLK', 'Blacklist rules'), ('CTL', 'Control files')], max_length=3)),
                ('category', models.ManyToManyField(to='signatures.Category')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.File')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signatures.Signature')),
            ],
        ),
    ]
