# Generated by Django 3.0.4 on 2020-03-30 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extention',
            new_name='hash',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='file',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='policy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='signatures.Policy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='issue',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signature',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='signatures.Policy'),
            preserve_default=False,
        ),
    ]
