# Generated by Django 3.0.4 on 2020-03-31 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_auto_20200330_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 21, 57, 16, 62871)),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 21, 57, 16, 62910)),
        ),
    ]
