# Generated by Django 3.0.4 on 2020-03-31 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_auto_20200331_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 25, 24, 335570)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('SIG', 'Malware signature'), ('WLS', 'Whitelist rules'), ('BLS', 'Blacklist rules'), ('CTL', 'Control files')], max_length=3),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 25, 24, 335609)),
        ),
    ]
