# Generated by Django 3.0.4 on 2020-03-31 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_auto_20200331_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 38, 44, 953087)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('SIG', 'Signature'), ('WLS', 'Whitelist'), ('BLS', 'Blacklist'), ('CGR', 'Control group')], max_length=3),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 31, 23, 38, 44, 953126)),
        ),
    ]
