# Generated by Django 3.0.4 on 2020-04-01 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0006_auto_20200331_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 26, 42, 556289)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 26, 42, 556329)),
        ),
    ]
