# Generated by Django 3.0.4 on 2020-04-01 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0007_auto_20200401_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 28, 2, 538839)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 0, 28, 2, 538882)),
        ),
    ]
