# Generated by Django 3.0.4 on 2020-04-01 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0008_auto_20200401_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 2, 19, 3, 922984)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 2, 19, 3, 923051)),
        ),
    ]
