# Generated by Django 3.0.4 on 2020-04-01 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0009_auto_20200401_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('TGT', 'Target'), ('ENG', 'Engine'), ('FSZ', 'FileSize'), ('ENT', 'EntryPoint'), ('SEC', 'NumberOfSections'), ('CON', 'Container'), ('INT', 'Intermediates')], default='TGT', max_length=3)),
                ('value', models.CharField(default='0', max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='subsign',
            name='order',
        ),
        migrations.RemoveField(
            model_name='subsign',
            name='signature',
        ),
        migrations.AddField(
            model_name='signature',
            name='subsigns',
            field=models.ManyToManyField(to='signatures.SubSign'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 4, 26, 1, 38971)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='issue',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('SIG', 'Signature'), ('WLS', 'Whitelist'), ('BLS', 'Blacklist'), ('CGR', 'Control group')], default='SIG', max_length=3),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 4, 26, 1, 39007)),
        ),
        migrations.AlterField(
            model_name='signature',
            name='logic',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='signature',
            name='policy',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'SIG'}, on_delete=django.db.models.deletion.CASCADE, to='signatures.Policy'),
        ),
        migrations.AlterField(
            model_name='subsign',
            name='size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subsign',
            name='type',
            field=models.CharField(choices=[('REG', 'Regular expression'), ('HEX', 'Hex string')], default='HEX', max_length=3),
        ),
        migrations.DeleteModel(
            name='TargetOption',
        ),
        migrations.AddField(
            model_name='signature',
            name='options',
            field=models.ManyToManyField(to='signatures.Option'),
        ),
    ]
