# Generated by Django 3.0.4 on 2020-04-01 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0010_auto_20200401_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 4, 31, 37, 69555)),
        ),
        migrations.AlterField(
            model_name='policy',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 4, 31, 37, 69592)),
        ),
    ]
