# Generated by Django 3.0.4 on 2020-04-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('TGT', 'Target'), ('ENG', 'Engine'), ('FSZ', 'FileSize'), ('ENT', 'EntryPoint'), ('SEC', 'NumberOfSections'), ('CON', 'Container'), ('INT', 'Intermediates')], default='TGT', max_length=3)),
                ('value', models.CharField(default='0', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('SIG', 'Signature'), ('WLS', 'Whitelist'), ('BLS', 'Blacklist'), ('CGR', 'Control group')], default='SIG', max_length=3)),
                ('categories', models.ManyToManyField(blank=True, to='hackroom.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REG', 'Regular expression'), ('HEX', 'Hex string')], default='HEX', max_length=3)),
                ('value', models.CharField(max_length=1024)),
                ('size', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic', models.CharField(default='0', max_length=128)),
                ('options', models.ManyToManyField(to='hackroom.Option')),
                ('policy', models.ForeignKey(blank=True, limit_choices_to={'type': 'SIG'}, on_delete=django.db.models.deletion.CASCADE, to='hackroom.Policy')),
                ('subsigns', models.ManyToManyField(to='hackroom.SubSign')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='infected')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackroom.Policy')),
            ],
        ),
    ]
