# Generated by Django 3.0.4 on 2020-04-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='policy',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'SIG'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackroom.Policy'),
        ),
    ]
